### ISSUE TITLE
how to get about.me user id

### ISSUE THREAD

**Issue by zhunipingan** [kite1988/aboutme#1]
hi! 
I am a student majoring in data mining. I am appreciate for you paper and code!
you say you used abput.me API, do you mean some Api provided for developers? I don't find these apis for deveoplers. I find I can only get access to one's homepage unless I konw his kickname in about.me, for example I can get the info about john by visiting about.me/john.
I want to know how to get enough users' nickname of aboutme, can you share me your solutions, or do you have some suggestions, thank you very much.
looking forward to you reply, thanks!!!

**Comment by kite1988** [comment]
Hi,

The about.me API was still accessible when we crawled the dataset (in 2013) but later the API was shut down.
